### ISSUE TITLE
Name DAT is not found, use name: DAT_basicsr!

### ISSUE THREAD

**Issue by AIisCool** [zhengchen1999/DAT#1]
```
Name DAT is not found, use name: DAT_basicsr!
Traceback (most recent call last):
  File "C:\DAT-main\basicsr\test.py", line 44, in <module>
    test_pipeline(root_path)
  File "C:\DAT-main\basicsr\test.py", line 34, in test_pipeline
    model = build_model(opt)
  File "C:\Python310\lib\site-packages\basicsr\models\__init__.py", line 26, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "C:\Python310\lib\site-packages\basicsr\models\sr_model.py", line 22, in __init__
    self.net_g = build_network(opt['network_g'])
  File "C:\Python310\lib\site-packages\basicsr\archs\__init__.py", line 22, in build_network
    net = ARCH_REGISTRY.get(network_type)(**opt)
  File "C:\Python310\lib\site-packages\basicsr\utils\registry.py", line 71, in get
    raise KeyError(f"No object named '{name}' found in '{self._name}' registry!")
KeyError: "No object named 'DAT' found in 'arch' registry!"

```

**Comment by zhengchen1999** [comment]
Hi.
Thanks for your interest in our work.
I think the reason for your error is that [Dependencies](https://github.com/zhengchen1999/DAT#dependencies) are not prepared. This project needs to be installed locally. Perform the following steps in sequence on the terminal.
```
git clone https://github.com/zhengchen1999/DAT.git
cd DAT
conda create -n DAT python=3.8
conda activate DAT
pip install -r requirements.txt
python setup.py develop
```
After that, you can run the program normally.
If you have any other problem, please let us know. Thanks.

**Comment by Julesaiyy** [comment]
Thank you very much for your wonderful work. May I ask why did I follow the prompts and still encounter the above situation? Looking forward to your reply.

**Comment by Asubayo** [comment]
I just tried it and got the same traceback logs.
Even though it is specified in requirements.txt, I had to manually run `conda install pytorch==1.8.0 torchvision==0.9.0 cudatoolkit=11.1 -c pytorch -c conda-forge`

**Comment by zhengchen1999** [comment]
Sorry for the late reply.

I think you don’t run the command <python setup.py develop> and step up environment successfully.

Can you provide the conda env after you run the command?

**Comment by Julesaiyy** [comment]
I am using an A5000 single card training and have followed the steps to achieve results. I am not sure what the problem is, but still cannot be solved?

**Comment by Julesaiyy** [comment]
I am using an A5000 single GPU training and have followed the steps to achieve results. I am not sure what the problem is, but still cannot be solved?

**Comment by zhengchen1999** [comment]
Is your pytorch installed successfully? (running other projects successfully).
Can you provide the log after running the command 'python setup.py develop'?

**Comment by Julesaiyy** [comment]
Of course, the following is the log after I run the command Python setup.py develop.

 python setup.py develop
/home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
running develop
/home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  easy_install.initialize_options(self)
/home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
running egg_info
writing basicsr.egg-info/PKG-INFO
writing dependency_links to basicsr.egg-info/dependency_links.txt
writing requirements to basicsr.egg-info/requires.txt
writing top-level names to basicsr.egg-info/top_level.txt
reading manifest file 'basicsr.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'basicsr.egg-info/SOURCES.txt'
/home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages/torch/utils/cpp_extension.py:369: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
running build_ext
Creating /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages/basicsr.egg-link (link to .)
basicsr 1.3.5 is already the active version in easy-install.pth

Installed /media/x9320/U128/DAT
Processing dependencies for basicsr==1.3.5
Searching for h5py==3.9.0
Best match: h5py 3.9.0
Adding h5py 3.9.0 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for einops==0.6.1
Best match: einops 0.6.1
Adding einops 0.6.1 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for timm==0.9.5
Best match: timm 0.9.5
Adding timm 0.9.5 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for yapf==0.40.1
Best match: yapf 0.40.1
Adding yapf 0.40.1 to easy-install.pth file
Installing yapf script to /home/x9320/anaconda3/envs/sr/bin
Installing yapf-diff script to /home/x9320/anaconda3/envs/sr/bin

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for tqdm==4.66.0
Best match: tqdm 4.66.0
Adding tqdm 4.66.0 to easy-install.pth file
Installing tqdm script to /home/x9320/anaconda3/envs/sr/bin

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for torchvision==0.9.0+cu111
Best match: torchvision 0.9.0+cu111
Adding torchvision 0.9.0+cu111 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for torch==1.8.0+cu111
Best match: torch 1.8.0+cu111
Adding torch 1.8.0+cu111 to easy-install.pth file
Installing convert-caffe2-to-onnx script to /home/x9320/anaconda3/envs/sr/bin
Installing convert-onnx-to-caffe2 script to /home/x9320/anaconda3/envs/sr/bin

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for tb-nightly==2.14.0a20230808
Best match: tb-nightly 2.14.0a20230808
Adding tb-nightly 2.14.0a20230808 to easy-install.pth file
Installing tensorboard script to /home/x9320/anaconda3/envs/sr/bin

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for scipy==1.10.1
Best match: scipy 1.10.1
Adding scipy 1.10.1 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for scikit-image==0.21.0
Best match: scikit-image 0.21.0
Adding scikit-image 0.21.0 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for requests==2.31.0
Best match: requests 2.31.0
Adding requests 2.31.0 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for PyYAML==6.0.1
Best match: PyYAML 6.0.1
Adding PyYAML 6.0.1 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for Pillow==10.0.0
Best match: Pillow 10.0.0
Adding Pillow 10.0.0 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for opencv-python==4.8.0.76
Best match: opencv-python 4.8.0.76
Adding opencv-python 4.8.0.76 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for numpy==1.24.4
Best match: numpy 1.24.4
Adding numpy 1.24.4 to easy-install.pth file
Installing f2py script to /home/x9320/anaconda3/envs/sr/bin
Installing f2py3 script to /home/x9320/anaconda3/envs/sr/bin
Installing f2py3.8 script to /home/x9320/anaconda3/envs/sr/bin

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for lmdb==1.4.1
Best match: lmdb 1.4.1
Adding lmdb 1.4.1 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for future==0.18.3
Best match: future 0.18.3
Adding future 0.18.3 to easy-install.pth file
Installing futurize script to /home/x9320/anaconda3/envs/sr/bin
Installing pasteurize script to /home/x9320/anaconda3/envs/sr/bin

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for addict==2.4.0
Best match: addict 2.4.0
Adding addict 2.4.0 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for safetensors==0.3.2
Best match: safetensors 0.3.2
Adding safetensors 0.3.2 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for huggingface-hub==0.16.4
Best match: huggingface-hub 0.16.4
Adding huggingface-hub 0.16.4 to easy-install.pth file
Installing huggingface-cli script to /home/x9320/anaconda3/envs/sr/bin

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for tomli==2.0.1
Best match: tomli 2.0.1
Adding tomli 2.0.1 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for platformdirs==3.10.0
Best match: platformdirs 3.10.0
Adding platformdirs 3.10.0 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for importlib-metadata==6.8.0
Best match: importlib-metadata 6.8.0
Adding importlib-metadata 6.8.0 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for typing-extensions==4.7.1
Best match: typing-extensions 4.7.1
Adding typing-extensions 4.7.1 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for wheel==0.38.4
Best match: wheel 0.38.4
Adding wheel 0.38.4 to easy-install.pth file
Installing wheel script to /home/x9320/anaconda3/envs/sr/bin

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for Werkzeug==2.3.6
Best match: Werkzeug 2.3.6
Adding Werkzeug 2.3.6 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for tensorboard-data-server==0.7.1
Best match: tensorboard-data-server 0.7.1
Adding tensorboard-data-server 0.7.1 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for setuptools==68.0.0
Best match: setuptools 68.0.0
Adding setuptools 68.0.0 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for protobuf==4.24.0
Best match: protobuf 4.24.0
Adding protobuf 4.24.0 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for Markdown==3.4.4
Best match: Markdown 3.4.4
Adding Markdown 3.4.4 to easy-install.pth file
Installing markdown_py script to /home/x9320/anaconda3/envs/sr/bin

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for google-auth-oauthlib==1.0.0
Best match: google-auth-oauthlib 1.0.0
Adding google-auth-oauthlib 1.0.0 to easy-install.pth file
Installing google-oauthlib-tool script to /home/x9320/anaconda3/envs/sr/bin

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for google-auth==2.22.0
Best match: google-auth 2.22.0
Adding google-auth 2.22.0 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for grpcio==1.56.2
Best match: grpcio 1.56.2
Adding grpcio 1.56.2 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for absl-py==1.4.0
Best match: absl-py 1.4.0
Adding absl-py 1.4.0 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for lazy-loader==0.3
Best match: lazy-loader 0.3
Adding lazy-loader 0.3 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for packaging==23.1
Best match: packaging 23.1
Adding packaging 23.1 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for PyWavelets==1.4.1
Best match: PyWavelets 1.4.1
Adding PyWavelets 1.4.1 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for tifffile==2023.7.10
Best match: tifffile 2023.7.10
Adding tifffile 2023.7.10 to easy-install.pth file
Installing lsm2bin script to /home/x9320/anaconda3/envs/sr/bin
Installing tiff2fsspec script to /home/x9320/anaconda3/envs/sr/bin
Installing tiffcomment script to /home/x9320/anaconda3/envs/sr/bin
Installing tifffile script to /home/x9320/anaconda3/envs/sr/bin

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for imageio==2.31.1
Best match: imageio 2.31.1
Adding imageio 2.31.1 to easy-install.pth file
Installing imageio_download_bin script to /home/x9320/anaconda3/envs/sr/bin
Installing imageio_remove_bin script to /home/x9320/anaconda3/envs/sr/bin

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for networkx==3.1
Best match: networkx 3.1
Adding networkx 3.1 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for certifi==2023.7.22
Best match: certifi 2023.7.22
Adding certifi 2023.7.22 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for urllib3==1.26.16
Best match: urllib3 1.26.16
Adding urllib3 1.26.16 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for idna==3.4
Best match: idna 3.4
Adding idna 3.4 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for charset-normalizer==3.2.0
Best match: charset-normalizer 3.2.0
Adding charset-normalizer 3.2.0 to easy-install.pth file
Installing normalizer script to /home/x9320/anaconda3/envs/sr/bin

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for fsspec==2023.6.0
Best match: fsspec 2023.6.0
Adding fsspec 2023.6.0 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for filelock==3.12.2
Best match: filelock 3.12.2
Adding filelock 3.12.2 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for zipp==3.16.2
Best match: zipp 3.16.2
Adding zipp 3.16.2 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for MarkupSafe==2.1.3
Best match: MarkupSafe 2.1.3
Adding MarkupSafe 2.1.3 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for requests-oauthlib==1.3.1
Best match: requests-oauthlib 1.3.1
Adding requests-oauthlib 1.3.1 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for six==1.16.0
Best match: six 1.16.0
Adding six 1.16.0 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for rsa==4.9
Best match: rsa 4.9
Adding rsa 4.9 to easy-install.pth file
Installing pyrsa-decrypt script to /home/x9320/anaconda3/envs/sr/bin
Installing pyrsa-encrypt script to /home/x9320/anaconda3/envs/sr/bin
Installing pyrsa-keygen script to /home/x9320/anaconda3/envs/sr/bin
Installing pyrsa-priv2pub script to /home/x9320/anaconda3/envs/sr/bin
Installing pyrsa-sign script to /home/x9320/anaconda3/envs/sr/bin
Installing pyrsa-verify script to /home/x9320/anaconda3/envs/sr/bin

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for pyasn1-modules==0.3.0
Best match: pyasn1-modules 0.3.0
Adding pyasn1-modules 0.3.0 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for cachetools==5.3.1
Best match: cachetools 5.3.1
Adding cachetools 5.3.1 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for oauthlib==3.2.2
Best match: oauthlib 3.2.2
Adding oauthlib 3.2.2 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Searching for pyasn1==0.5.0
Best match: pyasn1 0.5.0
Adding pyasn1 0.5.0 to easy-install.pth file

Using /home/x9320/anaconda3/envs/sr/lib/python3.8/site-packages
Finished processing dependencies for basicsr==1.3.5

**Comment by Julesaiyy** [comment]
> Is your pytorch installed successfully? (running other projects successfully). Can you provide the log after running the command `python setup.py develop`?

And I believe Python has been successfully installed, and other projects can also be used normally.

**Comment by zhengchen1999** [comment]
Is your conda env newly built? Judging from the log, your setup is successful. There is a possibility that you have installed BasicSR before, which caused a conflict.

**Comment by Julesaiyy** [comment]
> Is your conda env newly built? Judging from the log, your setup is successful. There is a possibility that you have installed BasicSR before, which caused a conflict.

According to your prompt, I have successfully resolved this issue. I hope future users will remember my painful lesson: never install basicsr on your own beforehand, as it will cause conflicts. Once again, I am grateful for the author's patient assistance and this impressive work.

**Comment by 2845764980** [comment]
> python setup.py develop

Hello, may I ask you use one gpu A5000, How long does it take to train?

**Comment by 2845764980** [comment]
Hello, How long does it takes to train?

**Comment by turbowenxuan** [comment]
> Sorry for the late reply.
> 
> I think you didn't run the command `python setup.py develop` and set up environment successfully.
> 
> Can you provide the conda env after you run the command?
> 
> PS: In some GPU servers (most do not need), pytorch needs to be installed separately. For example in 3090 GPU server, the complete commands is
> 
> ```
> conda create -n DAT python=3.8
> conda activate DAT
> pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio===0.8.0 -f https://download.pytorch.org/whl/torch_stable.html
> pip install -r requirements.txt (delete torch==1.8.0 and torchvision in requirements.txt)
> python setup.py develop
> ```
> 
> I run these commands locally, and can install the environment successfully without issue.

Is this the same operation in the Linux system? I rented a server from the Internet to run this project. But the problem is No object named 'DAT' found in 'arch' registry!

**Comment by zhengchen1999** [comment]
Linux operates like this. Your issue, still not successfully installed. It's recommended that you reinstall a new environment (executing `python setup.py develop` in the old environment might always fail).

**Comment by zhengchen1999** [comment]
> Hello, How long does it takes to train?
It can be seen from the log (in experiments file), there will be an estimated time corresponding to it.
