### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by azumeow** [zhengchen1999/DAT#44]
```
2024-06-12 03:45:45,495 INFO: Testing Single...
Traceback (most recent call last):
  File "basicsr/test.py", line 44, in <module>
    test_pipeline(root_path)
  File "basicsr/test.py", line 39, in test_pipeline
    model.validation(test_loader, current_iter=opt['name'], tb_logger=None, save_img=opt['val']['save_img'])
  File "/mnt/c/Users/Jian Yowen/Desktop/paper/DAT/basicsr/models/base_model.py", line 48, in 
validation
    self.nondist_validation(dataloader, current_iter, tb_logger, save_img)
  File "/mnt/c/Users/Jian Yowen/Desktop/paper/DAT/basicsr/models/sr_model.py", line 157, in nondist_validation
    self.test()
  File "/mnt/c/Users/Jian Yowen/Desktop/paper/DAT/basicsr/models/dat_model.py", line 21, in test
    self.output = self.net_g(self.lq)
  File "/home/azumeow/ENTER/envs/DAT/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/c/Users/Jian Yowen/Desktop/paper/DAT/basicsr/archs/dat_arch.py", line 847, in forward
    x = (x - self.mean) * self.img_range
RuntimeError: CUDA error: no kernel image is available for execution on the device
```
this is error message when executing "test_single_x2.yml", i use pertrain_models, and type is DAT. My CUDA is 11.5, and torch is 1.8.0, gpu is NVIDIA GeForce RTX 3060 Ti. Does CUDA necessarily need to use version 12.5, or is it another issue?

**Comment by zhengchen1999** [comment]
1. CUDA版本不需要最新的
2. 可能是默认安装的pytorch为cpu版本，需要明确指定：
```
pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio===0.8.0 -f https://download.pytorch.org/whl/torch_stable.html
pip install -r requirements.txt (delete torch==1.8.0 and torchvision in requirements.txt)

**Comment by azumeow** [comment]
謝謝您的回覆!
