### ISSUE TITLE
运行错误，数据集有问题。

### ISSUE THREAD

**Issue by gdsdfn75** [zhengchen1999/DAT#54]
大佬的这个工作非常好。我在复现的时候用了一个30图片的数据集，运行后出现以下错误
Traceback (most recent call last):
  File "basicsr/train.py", line 215, in <module>
    train_pipeline(root_path)
  File "basicsr/train.py", line 120, in train_pipeline
    result = create_train_val_dataloader(opt, logger)
  File "basicsr/train.py", line 35, in create_train_val_dataloader
    train_set = build_dataset(dataset_opt)
  File "E:\env\anaconda\envs\test001\lib\site-packages\basicsr-1.3.5-py3.8.egg\basicsr\data\__init__.py", line 34, in build_dataset
    dataset = DATASET_REGISTRY.get(dataset_opt['type'])(dataset_opt)
  File "E:\env\anaconda\envs\test001\lib\site-packages\basicsr-1.3.5-py3.8.egg\basicsr\data\paired_image_dataset.py", line 65, in __init__
    self.paths = paired_paths_from_folder([self.lq_folder, self.gt_folder], ['lq', 'gt'], self.filename_tmpl)
  File "E:\env\anaconda\envs\test001\lib\site-packages\basicsr-1.3.5-py3.8.egg\basicsr\data\data_util.py", line 195, in paired_paths_from_folder
    assert input_name in input_paths, f'{input_name} is not in {input_key}_paths.'
AssertionError: baseballfield091x4.png is not in lq_paths.
大佬能帮看一下，是哪里出错了吗？

**Comment by zhengchen1999** [comment]
你的数据包括LQ（低分辨率）和HQ（高分辨率）图片吗？
同时，命名格式需要注意LQ包含后缀'x4'。后缀可以通过修改 [filename_tmpl](https://github.com/zhengchen1999/DAT/blob/main/options/Train/train_DAT_2_x2.yml#L16) 进行调整。

**Comment by gdsdfn75** [comment]
> 你的数据包括LQ（低分辨率）和HQ（高分辨率）图片吗？ 同时，命名格式需要注意LQ包含后缀'x4'。后缀可以通过修改[filename_tmpl](https://github.com/zhengchen1999/DAT/blob/main/options/Train/train_DAT_2_x2.yml#L16)进行调整。

感谢大佬回复，是数据集命名的问题，已经解决了。
